create database task_two;
use task_two;
CREATE TABLE artists(artists_name varchar(20),age int,native_place varchar(20), current_place varchar(20),height int,weight int,salary float,number_of_movies int);
alter table artists add column number_of_seies int;
alter table artists add column number_of_awards int;
desc artists;
insert into artists values('punith',40,'bengaluru','bengaluru',170,80,1000000,45,10,50);
select*from artists;
insert into artists values('sudeep',50,'bengaluru','bengaluru',180,90,1500000,50,20,60);
select*from artists;
CREATE TABLE Generators(id int,brand varchar(20),power_source varchar(10),uses_for_product varchar(20),weight int,output_wattage int,special_feature varchar(20),voltage int, current_range int);
alter table Generators add column input int;
alter table Generators add column output int;
desc Generators;
insert into Generators values(1,'XLNT','batttery','steel',55080,3000,'portable',230,2,230,230);
select*from Generators;
insert into Generators values(2,'EF ECOFLOW','batttery','steel',48,2400,'portable',230,2,230,230);
select*from Generators;
CREATE TABLE CircuitBreakers(type_of_CB varchar(20),brand varchar(10),current_rating int,mounting_type varchar(20),dimensions varchar(10),height int,weight int,material varchar(20));
alter table CircuitBreakers add column input int;
alter table CircuitBreakers add column output int;
desc CircuitBreakers;
insert into CircuitBreakers values('air','schneider',25,'DIN','89d*41w*89',20,210,'bronze',230,6);
select*from CircuitBreakers;
insert into CircuitBreakers values('sf6','ABB',35,'dgv','79d*31w*79',20,210,'copper',415,10);
select*from CircuitBreakers;
CREATE TABLE Meters(id int,types_of_meter varchar(20),brand varchar(20),current_rating int,voltage_rating int,height int, weight int,input_type varchar(10),number_Of_phases varchar(10));
alter table Meters add column power_source varchar(20);
desc Meters;
insert into Meters values(1,'energy','amiciSense',10,230,10,20,'ac','single','mains','digital');
select*from Meters;
insert into Meters values(2,'watt','sechronide',20,415,20,30,'Dc','three','battery','analog');
select*from Meters;
CREATE TABLE Transformer(id int,volage_rating int,current_rating int, power_rating int,type_of_cooling varchar(10),number_of_phases int,type_of_winding varchar(10),type_of_structure varchar(10),type_of_mounting varchar(10));
alter table Transformer add column brand varchar(20);
alter table Transformer add column weight int;
desc Transformer;
insert into Transformer values(1,230,25,300,'air','1','wave','core','dic','abb',300);
select*from Transformer;
insert into Transformer values(2,415,20,1000,'oil','3','wound','core','dic','abb',400);
select*from Transformer;